export enum MessageType {
  SCAN_PAGE = 'SCAN_PAGE',
  GET_FIELD_MAP = 'GET_FIELD_MAP',
  FILL_FIELDS = 'FILL_FIELDS',
  GENERATE_COVER_LETTER = 'GENERATE_COVER_LETTER',
  GET_MATCH_SCORE = 'GET_MATCH_SCORE',
  GET_PROFILE = 'GET_PROFILE',
  SET_PROFILE = 'SET_PROFILE',
  GET_SETTINGS = 'GET_SETTINGS',
  SET_API_KEY = 'SET_API_KEY',
  VALIDATE_API_KEY = 'VALIDATE_API_KEY',
  PAGE_DETECTED = 'PAGE_DETECTED',
  FIELDS_SCANNED = 'FIELDS_SCANNED',
  GET_APPLICATIONS = 'GET_APPLICATIONS',
  ADD_APPLICATION = 'ADD_APPLICATION',
  UPDATE_APPLICATION = 'UPDATE_APPLICATION',
  DELETE_APPLICATION = 'DELETE_APPLICATION',
}

export const STORAGE_KEYS = {
  PROFILE: 'profile',
  SETTINGS: 'settings',
  APPLICATIONS: 'applications',
} as const;

export const LIMITS = {
  JOB_DESCRIPTION_MAX_CHARS: 20000,
  RESUME_MAX_CHARS: 30000,
  COVER_LETTER_MAX_WORDS: 400,
} as const;

export const GEMINI_MODEL = 'gemini-2.5-flash';

export const FIELD_LABEL_MAP: Record<string, string> = {
  // Personal info
  'first name': 'firstName',
  'first': 'firstName',
  'given name': 'firstName',
  'last name': 'lastName',
  'last': 'lastName',
  'family name': 'lastName',
  'surname': 'lastName',
  'full name': 'fullName',
  'name': 'fullName',
  'email': 'email',
  'email address': 'email',
  'e-mail': 'email',
  'phone': 'phone',
  'phone number': 'phone',
  'mobile': 'phone',
  'mobile number': 'phone',
  'telephone': 'phone',
  'location': 'location',
  'city': 'location',
  'address': 'location',
  'country': 'country',
  'country/region': 'country',

  // Links
  'linkedin': 'linkedinUrl',
  'linkedin url': 'linkedinUrl',
  'linkedin profile': 'linkedinUrl',
  'linkedin profile url': 'linkedinUrl',
  'portfolio': 'portfolioUrl',
  'portfolio url': 'portfolioUrl',
  'website': 'portfolioUrl',
  'website url': 'portfolioUrl',
  'personal website': 'portfolioUrl',
  'github': 'portfolioUrl',
  'github url': 'portfolioUrl',

  // Education
  'school': 'school',
  'university': 'school',
  'college': 'school',
  'school name': 'school',
  'degree': 'degree',
  'degree type': 'degree',
  'field of study': 'field',
  'major': 'field',
  'discipline': 'field',
  'area of study': 'field',
  'graduation year': 'graduationYear',
  'grad year': 'graduationYear',
  'year of graduation': 'graduationYear',
  'end date': 'graduationYear',
  'gpa': 'gpa',
  'grade point average': 'gpa',

  // Professional
  'current company': 'currentCompany',
  'company': 'currentCompany',
  'company name': 'currentCompany',
  'current title': 'currentTitle',
  'job title': 'currentTitle',
  'title': 'currentTitle',
  'current role': 'currentTitle',
  'years of experience': 'yearsExperience',
  'total experience': 'yearsExperience',
  'experience': 'yearsExperience',

  // Other
  'summary': 'summary',
  'cover letter': 'coverLetter',
  'resume': 'resumeText',
  'salary expectation': 'expectedSalary',
  'salary expectations': 'expectedSalary',
  'desired salary': 'expectedSalary',
  'start date': 'startDate',
  'available start date': 'startDate',
  'earliest start date': 'startDate',
};

export const COMMON_ANSWERS: Record<string, string> = {
  'authorized to work': 'workAuthorization',
  'legally authorized': 'workAuthorization',
  'work authorization': 'workAuthorization',
  'right to work': 'workAuthorization',
  'require sponsorship': 'needSponsorship',
  'need sponsorship': 'needSponsorship',
  'visa sponsorship': 'needSponsorship',
  'immigration sponsorship': 'needSponsorship',
  'expected salary': 'expectedSalary',
  'salary expectation': 'expectedSalary',
  'desired salary': 'expectedSalary',
  'compensation': 'expectedSalary',
  'start date': 'startDate',
  'earliest start': 'startDate',
  'available to start': 'startDate',
  'gender': 'gender',
  'race': 'ethnicity',
  'ethnicity': 'ethnicity',
  'veteran': 'veteranStatus',
  'disability': 'disabilityStatus',
};
